### ISSUE TITLE
gzip in accept-encoding request header?

### ISSUE THREAD

**Issue by meetar** [technoboy10/crossorigin.me#19]
I'm making a request through crossorigin.me and receiving a gzipped response which is undesirable in my case. I assume your "Accept-Encoding" request headers are including "gzip" – is there any way to disable this? Would it make sense to disable it by default, or is this use case common for your users?

Regardless – thanks for this project!

**Comment by schme16** [comment]
Hi @meetar: Are you able to explain what happens when your making your requests (i.e. why it's undesirable)?

**Comment by meetar** [comment]
Only that I receive zipped data rather than the plaintext response I get when I make the request directly, and I'd prefer not to have to implement an unzipper in my application when I know plaintext is available.

**Comment by schme16** [comment]
Hmm, just wondering how it would best be handled; are you able to set custom headers in your request? (i.e. is it a normal XHR request?)

Personally I'd prefer not to change the way the urls are formatted, but it might be an option to put a little config section before the urls, e.g. `https://crossorigin.me/[gzip:false]http://example.com` where everthing inside the sqare bracket (I chose square as they don't auto encode to % values, but curley brackets would be fine too, just looks messier in a browser, haha) would be a config option - this option at least makes the options easy to see and set, as well as backward compatible (if there are no options it just defaults to what it is right now)

What are your thoughts @technoboy10?

**Comment by technoboy10** [comment]
Hmm, that's actually a pretty cool concept. Lemme try it out on my local machine, and I'll get back to you.

**Comment by schme16** [comment]
@technoboy10: agreed; after I wrote the above I realized that headers, while neatest, are a nightmare to handle for most situations (hence why my PR went with the square brackets)

**Comment by meetar** [comment]
Interesting, that would certainly work for me. Otherwise there may be a way I could set custom headers –I was originally assuming that my headers were being ignored or overwritten by crossorigin.me, as the headers were the same in both cases, but I was only seeing the zip when using the proxy.

**Comment by technoboy10** [comment]
@meetar I've merged the gzip option PR - try using `https://crossorigin.me/[gzip:false]http://example.com`.

**Comment by meetar** [comment]
Still getting zips – is it possible that the browser is hijacking the request Accept value?

	Response Headers
	Access-Control-Allow-Credentials:false
	Access-Control-Allow-Headers:Content-Type
	Access-Control-Allow-Origin:*
	Cache-Control:max-age=86400, public
	CF-RAY:24e9561e438b06a9-EWR
	Connection:keep-alive
	Content-Encoding:gzip
	Content-Type:application/json; charset=utf-8
	Date:Wed, 02 Dec 2015 19:11:13 GMT
	Expires:Thu, 03 Dec 2015 19:11:13 GMT
	Server:cloudflare-nginx
	Transfer-Encoding:chunked
	Via:1.1 vegur
	X-Content-Type-Options:nosniff

	Request Headers
	Accept:*/*
	Accept-Encoding:gzip, deflate, sdch
	Accept-Language:en-US,en;q=0.8
	Cache-Control:no-cache
	Connection:keep-alive
	Host:crossorigin.me
	Origin:http://localhost:8080
	Pragma:no-cache
	User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

**Comment by schme16** [comment]
@meetar: Ohhhhhhh, it's Cloudflare doing it, hahaha!
You'll have to use the direct heroku link instead- atcors.herokuapp.com

@technoboy10: I just tried getting Cloudflare to stop auto gzipping everything: Other than completly disabling cloudflare, I simply couldn't turn it off; there's some cryptic message about it preserving the `content-encoding` [headers value](https://support.cloudflare.com/hc/en-us/articles/200168086-Does-CloudFlare-gzip-resources-), and I did find in the [HTTP/1.1 RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) that a value of `identity` is always accepted; so I've made the change to always send `identity` or `gzip`and have made a pull request

**Comment by meetar** [comment]
Hmmm, still coming back as zipped data even if I use the heroku links, although the Content-Type is now json 😅

Thanks for trying – I'm going to check with the source's admin and see if I can get any more information about this.

**Comment by meetar** [comment]
One other note: when I use `[gzip:true]` in the url, the browser at least knows to decode it, and I see JSON properly, which wasn't happening before. (Of course this doesn't help in the application, because the data is gzipped either way.)

**Comment by schme16** [comment]
@meetar: Let us know if you find out anything interesting from the source's admin

**Comment by 198819942014** [comment]
Accept-Encoding: gzip,deflate
Host: www.facebook.com
Connection: Keep-Alive
User-Agent: UserAgent
Cookie: fr=0xbwYYxHSn6AExpx7..BZ0DQn.TA.AAA.0.0.BZ0Dv7.AWV8zjm6; sb=JzTQWbjOrnOCklz3Zk96Z-TH
Cookie2: $Version=1
